### ISSUE TITLE
Getting error with version when trying to run the action

### ISSUE THREAD

**Issue by omri-ratson** [dieuhd/sonar-quality-gate#40]
Hello @dieuhd,
When I'm trying to run the action I get this error from our CLI:
![image](https://user-images.githubusercontent.com/109200667/206393924-2b45e7ff-097a-407b-8fe6-64c66f842583.png)
I'm also getting a similar error from the GitHub action:
![image](https://user-images.githubusercontent.com/109200667/206394478-fa3b48d2-1cc4-4913-ae49-ede35ebe13b3.png)

When searching for this error online I found these issues/fixes:
issue - https://github.com/salsita/node-pg-migrate/issues/863
resolved by - https://github.com/salsita/node-pg-migrate/commit/e2255778393359bba113aafec19aa471b7dfedaf
issue - https://github.com/AppThreat/cdxgen/issues/83
resolved by - https://github.com/AppThreat/cdxgen/commit/2e032248a23221d71f45942ef2ff41b740919b4d

I'm not sure why this is happening since I'm unfamiliar with Node configuration on that level.
I can't share with you my parameters for the run command since it has secrets but I do know they are working because I tried them with another Sonar GitHub action and they are working, I prefer to use yours if it's possible.

**Comment by dieuhd** [comment]
@omri-ratson 
Sorry i reply late.
- The first error: you are not install sonar-scanner
- The second error: you are not install java
Can you confirm that?

**Comment by JcCadet62** [comment]
same error

**Comment by dieuhd** [comment]
You can reference config: https://github.com/dieuhd/sonar-quality-gate#add-sonar-projectproperties
and result: #48
