### ISSUE TITLE
Github actions not taking secrets or hardcoded values

### ISSUE THREAD

**Issue by indrajeet-latthe** [dieuhd/sonar-quality-gate#42]
Hi @dieuhd, I'm trying to use this in Github actions and it seems while running the action is not taking secrets, I have even tried to hardcode the values and it still didn't work.

<img width="1104" alt="Screenshot 2023-05-09 at 10 59 15 AM" src="https://user-images.githubusercontent.com/107146797/237006784-ab87220e-13b7-4254-9815-55591e37c92e.png">

<img width="1079" alt="Screenshot 2023-05-09 at 11 26 57 AM" src="https://user-images.githubusercontent.com/107146797/237006862-d5460f8b-5a65-4953-ad35-90cb08a8921c.png">

Surpassingly it works if I create sonar-project.properties file and put parameters there, but I get the following error, though it does run sensors but has a problem while generating the report.

---- generate report ----
Error: Request failed with status code 403

The goal here would be to be able to successfully use secrets and generate the report.

**Comment by sanchit315** [comment]
I got same error

**Comment by sanchit315** [comment]
you got any solution @indrajeet-latthe

**Comment by dieuhd** [comment]
@sanchit315 @indrajeet-latthe 
You need add file `sonar-project.properties` in your source code.
Please read document here: https://github.com/dieuhd/sonar-quality-gate#add-sonar-projectproperties 

Results: https://github.com/dieuhd/sonar-quality-gate/pull/48
