### ISSUE TITLE
---- generate report ---- Error: Request failed with status code 403

### ISSUE THREAD

**Issue by pleiojk** [dieuhd/sonar-quality-gate#49]
What do I need to set for the generated report to be written ? 

#Action Log
 _   _   _                                     _          
   __ _   _   _    __ _  | | (_) | |_   _   _            __ _    __ _  | |_    ___ 
  / _` | | | | |  / _` | | | | | | __| | | | |  _____   / _` |  / _` | | __|  / _ \
 | (_| | | |_| | | (_| | | | | | | |_  | |_| | |_____| | (_| | | (_| | | |_  |  __/
  \__, |  \__,_|  \__,_| |_| |_|  \__|  \__, |          \__, |  \__,_|  \__|  \___|
     |_|                                |___/           |___/                      
(node:10) Warning: "version" is a reserved word.
Please do one of the following:
- Disable version with `yargs.version(false)` if using "version" as an option
- Use the built-in `yargs.version` method instead (if applicable)
- Use a different option key
https://yargs.js.org/docs/#api-reference-version
(Use `node --trace-warnings ...` to show where the warning was created)
INFO: Scanner configuration file: /opt/sonar-scanner/conf/sonar-scanner.properties
INFO: Project root configuration file: /github/workspace/sonar-project.properties
INFO: SonarScanner 4.6.2.2472
INFO: Java 11.0.14 Alpine (64-bit)
INFO: Linux 6.2.0-1016-azure amd64
INFO: User cache: /opt/sonar-scanner/.sonar/cache
INFO: Scanner configuration file: /opt/sonar-scanner/conf/sonar-scanner.properties
INFO: Project root configuration file: /github/workspace/sonar-project.properties
INFO: Analyzing on SonarQube server 10.2.1.78527
INFO: Default locale: "en_US", source code encoding: "UTF-8" (analysis is platform dependent)
INFO: Load global settings
INFO: Load global settings (done) | time=267ms
INFO: Server id: 5B260B62-AYvTSFWch3MZIUUjRIvS
INFO: User cache: /opt/sonar-scanner/.sonar/cache
INFO: Load/download plugins
INFO: Load plugins index
INFO: Load plugins index (done) | time=108ms
INFO: Load/download plugins (done) | time=34259ms
WARN: SonarScanner will require Java 17 to run, starting in SonarQube 10.3
INFO: Process project properties
INFO: Process project properties (done) | time=1ms
INFO: Execute project builders
INFO: Execute project builders (done) | time=6ms
INFO: Project key: ***
INFO: Base dir: /github/workspace
INFO: Working dir: /github/workspace/.scannerwork
INFO: Load project settings for component key: '***'
INFO: Load project settings for component key: '***' (done) | time=83ms
INFO: Auto-configuring with CI 'Github Actions'
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=107ms
INFO: Load active rules
INFO: Load active rules (done) | time=2733ms
INFO: Load analysis cache
INFO: Load analysis cache | time=101ms
WARN: The property 'sonar.login' is deprecated and will be removed in the future. Please use the 'sonar.token' property instead when passing a token.
INFO: Load project repositories
INFO: Load project repositories (done) | time=82ms
INFO: Indexing files...
INFO: Project configuration:
INFO: 72 files indexed
INFO: 0 files ignored because of scm ignore settings
INFO: Quality profile for css: Sonar way
INFO: Quality profile for js: Sonar way
INFO: Quality profile for json: Sonar way
INFO: Quality profile for php: Sonar way
INFO: Quality profile for xml: Sonar way
INFO: ------------- Run sensors on module ***
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=84ms
INFO: Sensor JaCoCo XML Report Importer [jacoco]
INFO: 'sonar.coverage.jacoco.xmlReportPaths' is not defined. Using default locations: target/site/jacoco/jacoco.xml,target/site/jacoco-it/jacoco.xml,build/reports/jacoco/test/jacocoTestReport.xml
INFO: No report imported, no coverage information will be imported by JaCoCo XML Report Importer
INFO: Sensor JaCoCo XML Report Importer [jacoco] (done) | time=5ms
INFO: Sensor IaC CloudFormation Sensor [iac]
INFO: 0 source files to be analyzed
INFO: 0/0 source files have been analyzed
INFO: Sensor IaC CloudFormation Sensor [iac] (done) | time=86ms
INFO: Sensor IaC Kubernetes Sensor [iac]
INFO: 0 source files to be analyzed
INFO: 0/0 source files have been analyzed
INFO: Sensor IaC Kubernetes Sensor [iac] (done) | time=9ms
INFO: Sensor IaC AzureResourceManager Sensor [iac]
INFO: 0 source files to be analyzed
INFO: 0/0 source files have been analyzed
INFO: Sensor IaC AzureResourceManager Sensor [iac] (done) | time=99ms
INFO: Sensor JavaScript/TypeScript analysis [javascript]
WARN: Using Node.js version 14 to execute analysis is deprecated and will stop being supported no earlier than May 1st, 2023. Please upgrade to a newer LTS version of Node.js [16, 18]
INFO: Found 0 tsconfig.json file(s): []
INFO: Creating TypeScript program
INFO: TypeScript configuration file /tmp/tmp-68-D32iu6hfJXFu
INFO: 3 source files to be analyzed
INFO: Creating TypeScript program (done) | time=841ms
INFO: Starting analysis with current program
INFO: Analyzed 3 file(s) with current program
INFO: 3/3 source files have been analyzed
INFO: Hit the cache for 0 out of 3
INFO: Miss the cache for 3 out of 3: ANALYSIS_MODE_INELIGIBLE [3/3]
INFO: Sensor JavaScript/TypeScript analysis [javascript] (done) | time=7687ms
INFO: Sensor CSS Rules [javascript]
INFO: 58 source files to be analyzed
INFO: 58/58 source files have been analyzed
INFO: Hit the cache for 0 out of 0
INFO: Miss the cache for 0 out of 0
INFO: Sensor CSS Rules [javascript] (done) | time=855ms
INFO: Sensor CSS Metrics [javascript]
INFO: Sensor CSS Metrics [javascript] (done) | time=11ms
INFO: Sensor C# Project Type Information [csharp]
INFO: Sensor C# Project Type Information [csharp] (done) | time=1ms
INFO: Sensor C# Analysis Log [csharp]
INFO: Sensor C# Analysis Log [csharp] (done) | time=16ms
INFO: Sensor C# Properties [csharp]
INFO: Sensor C# Properties [csharp] (done) | time=1ms
INFO: Sensor HTML [web]
INFO: Sensor HTML [web] (done) | time=91ms
INFO: Sensor XML Sensor [xml]
INFO: 1 source file to be analyzed
INFO: 1/1 source file has been analyzed
INFO: Sensor XML Sensor [xml] (done) | time=186ms
INFO: Sensor PHP sensor [php]
INFO: Starting PHP symbol indexer
INFO: 57 source files to be analyzed
INFO: 57/57 source files have been analyzed
INFO: Cached information of global symbols will be used for 0 out of 57 files. Global symbols were recomputed for the remaining files.
INFO: Starting PHP rules
INFO: 57 source files to be analyzed
INFO: 57/57 source files have been analyzed
INFO: The PHP analyzer was able to leverage cached data from previous analyses for 0 out of 57 files. These files were not parsed.
INFO: Sensor PHP sensor [php] (done) | time=2174ms
INFO: Sensor Analyzer for "php.ini" files [php]
INFO: Sensor Analyzer for "php.ini" files [php] (done) | time=4ms
INFO: Sensor PHPUnit report sensor [php]
INFO: No PHPUnit tests reports provided (see 'sonar.php.tests.reportPath' property)
INFO: No PHPUnit coverage reports provided (see 'sonar.php.coverage.reportPaths' property)
WARN: PHPUnit test cases are detected. Make sure to specify test sources via `sonar.test` to get more precise analysis results.
INFO: Sensor PHPUnit report sensor [php] (done) | time=5ms
INFO: Sensor TextAndSecretsSensor [text]
INFO: 65 source files to be analyzed
INFO: 65/65 source files have been analyzed
INFO: Sensor TextAndSecretsSensor [text] (done) | time=1005ms
INFO: Sensor VB.NET Project Type Information [vbnet]
INFO: Sensor VB.NET Project Type Information [vbnet] (done) | time=2ms
INFO: Sensor VB.NET Analysis Log [vbnet]
INFO: Sensor VB.NET Analysis Log [vbnet] (done) | time=25ms
INFO: Sensor VB.NET Properties [vbnet]
INFO: Sensor VB.NET Properties [vbnet] (done) | time=1ms
INFO: Sensor IaC Docker Sensor [iac]
INFO: 0 source files to be analyzed
INFO: 0/0 source files have been analyzed
INFO: Sensor IaC Docker Sensor [iac] (done) | time=42ms
INFO: ------------- Run sensors on project
INFO: Sensor Analysis Warnings import [csharp]
INFO: Sensor Analysis Warnings import [csharp] (done) | time=1ms
INFO: Sensor Zero Coverage Sensor
INFO: Sensor Zero Coverage Sensor (done) | time=13ms
INFO: CPD Executor 24 files had no CPD blocks
INFO: CPD Executor Calculating CPD for 36 files
INFO: CPD Executor CPD calculation finished (done) | time=26ms
INFO: Analysis report generated in 93ms, dir size=331.0 kB
INFO: Analysis report compressed in 169ms, zip size=[171](https://github.com/pleiojk/docker-sast-demo/actions/runs/6907493671/job/18794931486#step:4:172).5 kB
INFO: Analysis report uploaded in 425ms
INFO: ANALYSIS SUCCESSFUL, you can find the results at: ***/dashboard?id=***
INFO: Note that you will be able to access the updated dashboard once the server has processed the submitted analysis report
INFO: More about the report processing at ***/api/ce/task?id=AYveeplwmgNU2jTigVH-
INFO: Analysis total time: 25.609 s
INFO: ------------------------------------------------------------------------
INFO: EXECUTION SUCCESS
INFO: ------------------------------------------------------------------------
INFO: Total time: 1:09.[227](https://github.com/pleiojk/docker-sast-demo/actions/runs/6907493671/job/18794931486#step:4:228)s
INFO: Final Memory: 22M/77M
INFO: ------------------------------------------------------------------------
error code = 0
---- generate report ----
Error: Request failed with status code 403

#Project Properties 
sonar.projectKey=[redacted]
sonar.host.url=[redacted]

#build.yml
name: Check sonarqube
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up Sonar Quality Gate
        uses: dieuhd/sonar-quality-gate@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_URL: "https://api.github.com"
          GIT_TOKEN: ${{ secrets.GH_TOKEN }} <-- Generated Token with 
          SONAR_URL: ${{ secrets.SONAR_URL }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
        with:
          login:  ${{ secrets.SONAR_TOKEN }}
          url: ${{ secrets.SONAR_URL }}
          projectKey: ${{ secrets.SONAR_PROJECT_KEY }}

**Comment by hblab-dieuhd** [comment]
@pleiojk 
> Error: Request failed with status code 403
The error mean it has not permission to access github or sonar. Please check `GIT_TOKEN` or `SONAR_TOKEN `
