### ISSUE TITLE
Request failed with status code 401

### ISSUE THREAD

**Issue by gustavo1020** [dieuhd/sonar-quality-gate#51]
Hello

I hope this message finds you well. I'm currently facing an issue while working with [[sonar-quality-gate](https://github.com/dieuhd/sonar-quality-gate)], and I would greatly appreciate any help or guidance you can provide.

I have verified all my tokens, and they have passed successfully through a request to the GitHub API

-INFO: QUALITY GATE STATUS: PASSED - View details on https://sonarcloud.io/dashboard?-******
-INFO: Analysis total time: 19.561 s
-INFO: ------------------------------------------------------------------------
-INFO: EXECUTION SUCCESS
-INFO: ------------------------------------------------------------------------
-INFO: Total time: 23.241s
-INFO: Final Memory: 18M/67M
-INFO: ------------------------------------------------------------------------
**Error Details:**
- Error Code: 0
- Description: Request failed with status code 401

Thank you in advance for your time and support.

**Comment by dieuhd** [comment]
@gustavo1020 
> Description: Request failed with status code 401

it's mean “401 Error Unauthorized Access"
You need check environment `GIT_TOKEN`
